# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main


stages:
  - stage: Build
    jobs:
      - job: Build
        pool: default
        steps:
        - task: Npm@1
          inputs:
            command: 'custom'
            customCommand: 'install -D tailwindcss postcss autoprefixer'
        - task: Npm@1
          inputs:
            command: 'custom'
            customCommand: 'run build'
        - task: Npm@1
          inputs:
            command: 'publish'
            workingDir: './dist'
            publishRegistry: 'useFeed'
            publishFeed: 'b31e7855-31ce-46bc-8fc5-f7e730e923d8/dce593ee-ee82-4791-b674-ad0518e01834'